export const FETCHING_REQUEST = 'FETCHING_REQUEST';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';
export const SESSION_VALID = 'SESSION_VALID';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const WHOAMI = 'WHOAMI';
export const WHATAMI = 'WHATAMI';
export const REGISTER = 'REGISTER';
export const RESET = 'RESET';
export const REQ_RESET = 'REQ_RESET';
export const VERSION = 'VERSION';
export const LIVE = 'LIVE';
export const GPS = 'GPS';
export const IMEITYPE = 'IMEITYPE';

export const TMP_REGISTRASI = 'TMP_REGISTRASI';
export const TMP_REGISTRASI_COMPANY = 'TMP_REGISTRASI_COMPANY';
export const TMP_REGISTRASI_REMOVE = 'TMP_REGISTRASI_REMOVE';
export const TMP_RESET = 'TMP_RESET';
export const TMP_PHOTO = 'TMP_PHOTO';
export const TMP_PHOTO_REMOVE = 'TMP_PHOTO_REMOVE';

export const ABSENSI_CREATE = 'ABSENSI_CREATE';
export const ABSENSI_ALL_BY7 = 'ABSENSI_ALL_BY7';
export const ABSENSI_ALL_PERCOMPANY = 'ABSENSI_ALL_PERCOMPANY';
export const ABSENSI_ALL_PERCOMPANY2 = 'ABSENSI_ALL_PERCOMPANY2';
export const ABSENSI_ALL_PERCOMPANY_REFRESH = 'ABSENSI_ALL_PERCOMPANY_REFRESH';
export const ABSENSI_LOADING = 'ABSENSI_LOADING';
export const ABSENSI_REFRESHING = 'ABSENSI_REFRESHING';

export const USER_PERCOMPANY = 'USER_PERCOMPANY';
export const USER_PERCOMPANY2 = 'USER_PERCOMPANY2';
export const USER_PERCOMPANY_REFRESH = 'USER_PERCOMPANY_REFRESH';
export const USER_PERCOMPANY_LOADING = 'USER_PERCOMPANY_LOADING';
export const USER_PERCOMPANY_REFRESHING = 'USER_PERCOMPANY_REFRESHING';
export const USER_PERCOMPANY_ADMIN = 'USER_PERCOMPANY_ADMIN';
export const USER_PERCOMPANY_ADMIN_LOADING = 'USER_PERCOMPANY_ADMIN_LOADING';

export const CLEAR_IMEI = 'CLEAR_IMEI';
export const CLEAR_GPS = 'CLEAR_GPS';

export const TIME_GET = 'TIME_GET';
export const TIME_SET = 'TIME_SET';

export const CARD = 'CARD';

export const FITURE_GET = 'FITURE_GET';
export const FITURE_SET = 'FITURE_SET';
export const FITURE_ACTIVE = 'FITURE_ACTIVE';

export const HEALTH_Q = 'HEALTH_Q';

export const TRACKING = 'TRACKING';

export const GUESTUSER = 'GUESTUSER';
export const GUESTADMIN = 'GUESTADMIN';
export const GUESTADMIN_LOADING = 'GUESTADMIN_LOADING';
export const GUESTADMIN_REFRESHING = 'GUESTADMIN_REFRESHING';
export const GUESTADMIN_REFRESH = 'GUESTADMIN_REFRESH';
export const REGISTERGUEST = 'REGISTERGUEST';
export const GUESTCHECK = 'GUESTCHECK';
export const GUESTMEETING = 'GUESTMEETING';
export const TMPGUEST = 'TMPGUEST';
export const TMPGUESTPHOTO = 'TMPGUESTPHOTO';
